name: Dataform Compile

on: 
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
    compile:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code into workspace directory
            uses: actions/checkout@v4

          - name: Install Dataform dependencies
            uses: docker://dataformco/dataform:2.4.2
            with:
                args: install
          - name: Run dataform compile
            uses: docker://dataformco/dataform:2.4.2
            with:
                args: compile
