name: Dataform Schema Validation

on: 
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
    compile:
        runs-on: ubuntu-latest
        permissions:
         contents: 'read'
         id-token: 'write'

        steps:
          - name: Checkout code into workspace directory
            uses: actions/checkout@v4
     
          - name: Install Dataform dependencies
            uses: docker://dataformco/dataform:2.8.3
            with:
                args: install

          - name: Authenticate Google
            uses: 'google-github-actions/auth@v2'
            with:
              credentials_json: '${{ secrets.GCP_SECRET }}'

          - name: Write credentials file
            run: echo '${{ secrets.GCP_SECRET }}' >> .df-credentials.json

  
          - name: Execute Dataform dry run (Schema Validation)
            uses: docker://dataformco/dataform:2.8.3
            with:
                args: run --dry-run